version: 2.1
jobs:
  apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:1.2.0-beta1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform init -input=false
            terraform apply 
      - persist_to_workspace:
          root: .
          paths:
            - .
  destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:1.2.0-beta1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform destroy -var-file variables.tfvars

workflows:
  plan_approve_apply:
    jobs:
      - apply:
          context: tfc-dev
      - hold-apply:
          context: tfc-dev
          type: approval
          requires:
            - apply
      # - plan-destroy:
      #     context: tfc-dev
      #     requires:
      #       - apply
      # - hold-destroy:
      #     context: tfc-dev
      #     type: approval
      #     requires:
      #       - plan-destroy
      # - destroy:
      #     context: tfc-dev
